/**
 * generated by Xtext 2.36.0
 */
package simplepdl.xtext.simplePDL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import simplepdl.xtext.simplePDL.SimplePDLPackage;
import simplepdl.xtext.simplePDL.WorkDefinition;
import simplepdl.xtext.simplePDL.WorkSequence;
import simplepdl.xtext.simplePDL.WorkSequenceType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Work Sequence</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl#getLinkType <em>Link Type</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl#getSuccessor <em>Successor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkSequenceImpl extends ProcessElementImpl implements WorkSequence
{
  /**
   * The cached value of the '{@link #getLinkType() <em>Link Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinkType()
   * @generated
   * @ordered
   */
  protected WorkSequenceType linkType;

  /**
   * The cached value of the '{@link #getPredecessor() <em>Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredecessor()
   * @generated
   * @ordered
   */
  protected WorkDefinition predecessor;

  /**
   * The cached value of the '{@link #getSuccessor() <em>Successor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuccessor()
   * @generated
   * @ordered
   */
  protected WorkDefinition successor;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkSequenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimplePDLPackage.Literals.WORK_SEQUENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkSequenceType getLinkType()
  {
    return linkType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLinkType(WorkSequenceType newLinkType, NotificationChain msgs)
  {
    WorkSequenceType oldLinkType = linkType;
    linkType = newLinkType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE, oldLinkType, newLinkType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLinkType(WorkSequenceType newLinkType)
  {
    if (newLinkType != linkType)
    {
      NotificationChain msgs = null;
      if (linkType != null)
        msgs = ((InternalEObject)linkType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE, null, msgs);
      if (newLinkType != null)
        msgs = ((InternalEObject)newLinkType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE, null, msgs);
      msgs = basicSetLinkType(newLinkType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE, newLinkType, newLinkType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinition getPredecessor()
  {
    if (predecessor != null && predecessor.eIsProxy())
    {
      InternalEObject oldPredecessor = (InternalEObject)predecessor;
      predecessor = (WorkDefinition)eResolveProxy(oldPredecessor);
      if (predecessor != oldPredecessor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SimplePDLPackage.WORK_SEQUENCE__PREDECESSOR, oldPredecessor, predecessor));
      }
    }
    return predecessor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinition basicGetPredecessor()
  {
    return predecessor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPredecessor(WorkDefinition newPredecessor)
  {
    WorkDefinition oldPredecessor = predecessor;
    predecessor = newPredecessor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimplePDLPackage.WORK_SEQUENCE__PREDECESSOR, oldPredecessor, predecessor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinition getSuccessor()
  {
    if (successor != null && successor.eIsProxy())
    {
      InternalEObject oldSuccessor = (InternalEObject)successor;
      successor = (WorkDefinition)eResolveProxy(oldSuccessor);
      if (successor != oldSuccessor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SimplePDLPackage.WORK_SEQUENCE__SUCCESSOR, oldSuccessor, successor));
      }
    }
    return successor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinition basicGetSuccessor()
  {
    return successor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuccessor(WorkDefinition newSuccessor)
  {
    WorkDefinition oldSuccessor = successor;
    successor = newSuccessor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimplePDLPackage.WORK_SEQUENCE__SUCCESSOR, oldSuccessor, successor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE:
        return basicSetLinkType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE:
        return getLinkType();
      case SimplePDLPackage.WORK_SEQUENCE__PREDECESSOR:
        if (resolve) return getPredecessor();
        return basicGetPredecessor();
      case SimplePDLPackage.WORK_SEQUENCE__SUCCESSOR:
        if (resolve) return getSuccessor();
        return basicGetSuccessor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE:
        setLinkType((WorkSequenceType)newValue);
        return;
      case SimplePDLPackage.WORK_SEQUENCE__PREDECESSOR:
        setPredecessor((WorkDefinition)newValue);
        return;
      case SimplePDLPackage.WORK_SEQUENCE__SUCCESSOR:
        setSuccessor((WorkDefinition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE:
        setLinkType((WorkSequenceType)null);
        return;
      case SimplePDLPackage.WORK_SEQUENCE__PREDECESSOR:
        setPredecessor((WorkDefinition)null);
        return;
      case SimplePDLPackage.WORK_SEQUENCE__SUCCESSOR:
        setSuccessor((WorkDefinition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimplePDLPackage.WORK_SEQUENCE__LINK_TYPE:
        return linkType != null;
      case SimplePDLPackage.WORK_SEQUENCE__PREDECESSOR:
        return predecessor != null;
      case SimplePDLPackage.WORK_SEQUENCE__SUCCESSOR:
        return successor != null;
    }
    return super.eIsSet(featureID);
  }

} //WorkSequenceImpl
