/**
 * generated by Xtext 2.36.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AC Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.ACResource#getResource <em>Resource</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.ACResource#getResourceQuantity <em>Resource Quantity</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getACResource()
 * @model
 * @generated
 */
public interface ACResource extends EObject
{
  /**
   * Returns the value of the '<em><b>Resource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' reference.
   * @see #setResource(Resource)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getACResource_Resource()
   * @model
   * @generated
   */
  Resource getResource();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.ACResource#getResource <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource</em>' reference.
   * @see #getResource()
   * @generated
   */
  void setResource(Resource value);

  /**
   * Returns the value of the '<em><b>Resource Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Quantity</em>' attribute.
   * @see #setResourceQuantity(int)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getACResource_ResourceQuantity()
   * @model
   * @generated
   */
  int getResourceQuantity();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.ACResource#getResourceQuantity <em>Resource Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Quantity</em>' attribute.
   * @see #getResourceQuantity()
   * @generated
   */
  void setResourceQuantity(int value);

} // ACResource
