/**
 * generated by Xtext 2.36.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcessElement()
 * @model
 * @generated
 */
public interface ProcessElement extends EObject
{
} // ProcessElement
