/**
 * generated by Xtext 2.36.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see simplepdl.xtext.simplePDL.SimplePDLFactory
 * @model kind="package"
 * @generated
 */
public interface SimplePDLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simplePDL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/simplepdl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simplePDL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimplePDLPackage eINSTANCE = simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl.init();

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ProcessImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__NAME = 0;

  /**
   * The feature id for the '<em><b>Process Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__PROCESS_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ProcessElementImpl <em>Process Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ProcessElementImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getProcessElement()
   * @generated
   */
  int PROCESS_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Process Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.GuidanceImpl <em>Guidance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.GuidanceImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getGuidance()
   * @generated
   */
  int GUIDANCE = 2;

  /**
   * The feature id for the '<em><b>Elements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUIDANCE__ELEMENTS = PROCESS_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUIDANCE__TEXT = PROCESS_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Guidance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUIDANCE_FEATURE_COUNT = PROCESS_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl <em>Work Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkDefinition()
   * @generated
   */
  int WORK_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__NAME = PROCESS_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Resources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__RESOURCES = PROCESS_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Work Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION_FEATURE_COUNT = PROCESS_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl <em>Work Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.WorkSequenceImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequence()
   * @generated
   */
  int WORK_SEQUENCE = 4;

  /**
   * The feature id for the '<em><b>Link Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__LINK_TYPE = PROCESS_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__PREDECESSOR = PROCESS_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__SUCCESSOR = PROCESS_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Work Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_FEATURE_COUNT = PROCESS_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ResourceImpl <em>Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ResourceImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getResource()
   * @generated
   */
  int RESOURCE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__NAME = PROCESS_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__QUANTITY = PROCESS_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE_FEATURE_COUNT = PROCESS_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ACResourceImpl <em>AC Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ACResourceImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getACResource()
   * @generated
   */
  int AC_RESOURCE = 6;

  /**
   * The feature id for the '<em><b>Resource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AC_RESOURCE__RESOURCE = 0;

  /**
   * The feature id for the '<em><b>Resource Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AC_RESOURCE__RESOURCE_QUANTITY = 1;

  /**
   * The number of structural features of the '<em>AC Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AC_RESOURCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.WorkSequenceTypeImpl <em>Work Sequence Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.WorkSequenceTypeImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequenceType()
   * @generated
   */
  int WORK_SEQUENCE_TYPE = 7;

  /**
   * The feature id for the '<em><b>Start To Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_TYPE__START_TO_START = 0;

  /**
   * The feature id for the '<em><b>Finish To Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_TYPE__FINISH_TO_START = 1;

  /**
   * The feature id for the '<em><b>Start To Finish</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_TYPE__START_TO_FINISH = 2;

  /**
   * The feature id for the '<em><b>Finish To Finish</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_TYPE__FINISH_TO_FINISH = 3;

  /**
   * The number of structural features of the '<em>Work Sequence Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_TYPE_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see simplepdl.xtext.simplePDL.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Process#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getName()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Name();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.Process#getProcessElements <em>Process Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Process Elements</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getProcessElements()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_ProcessElements();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.ProcessElement <em>Process Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process Element</em>'.
   * @see simplepdl.xtext.simplePDL.ProcessElement
   * @generated
   */
  EClass getProcessElement();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Guidance <em>Guidance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guidance</em>'.
   * @see simplepdl.xtext.simplePDL.Guidance
   * @generated
   */
  EClass getGuidance();

  /**
   * Returns the meta object for the reference list '{@link simplepdl.xtext.simplePDL.Guidance#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Elements</em>'.
   * @see simplepdl.xtext.simplePDL.Guidance#getElements()
   * @see #getGuidance()
   * @generated
   */
  EReference getGuidance_Elements();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Guidance#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see simplepdl.xtext.simplePDL.Guidance#getText()
   * @see #getGuidance()
   * @generated
   */
  EAttribute getGuidance_Text();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.WorkDefinition <em>Work Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Definition</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition
   * @generated
   */
  EClass getWorkDefinition();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getName()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.WorkDefinition#getResources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Resources</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getResources()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_Resources();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.WorkSequence <em>Work Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Sequence</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence
   * @generated
   */
  EClass getWorkSequence();

  /**
   * Returns the meta object for the containment reference '{@link simplepdl.xtext.simplePDL.WorkSequence#getLinkType <em>Link Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Link Type</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getLinkType()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_LinkType();

  /**
   * Returns the meta object for the reference '{@link simplepdl.xtext.simplePDL.WorkSequence#getPredecessor <em>Predecessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Predecessor</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getPredecessor()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_Predecessor();

  /**
   * Returns the meta object for the reference '{@link simplepdl.xtext.simplePDL.WorkSequence#getSuccessor <em>Successor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Successor</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getSuccessor()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_Successor();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Resource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resource</em>'.
   * @see simplepdl.xtext.simplePDL.Resource
   * @generated
   */
  EClass getResource();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Resource#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.Resource#getName()
   * @see #getResource()
   * @generated
   */
  EAttribute getResource_Name();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Resource#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see simplepdl.xtext.simplePDL.Resource#getQuantity()
   * @see #getResource()
   * @generated
   */
  EAttribute getResource_Quantity();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.ACResource <em>AC Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AC Resource</em>'.
   * @see simplepdl.xtext.simplePDL.ACResource
   * @generated
   */
  EClass getACResource();

  /**
   * Returns the meta object for the reference '{@link simplepdl.xtext.simplePDL.ACResource#getResource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Resource</em>'.
   * @see simplepdl.xtext.simplePDL.ACResource#getResource()
   * @see #getACResource()
   * @generated
   */
  EReference getACResource_Resource();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.ACResource#getResourceQuantity <em>Resource Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Resource Quantity</em>'.
   * @see simplepdl.xtext.simplePDL.ACResource#getResourceQuantity()
   * @see #getACResource()
   * @generated
   */
  EAttribute getACResource_ResourceQuantity();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.WorkSequenceType <em>Work Sequence Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Sequence Type</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @generated
   */
  EClass getWorkSequenceType();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getStartToStart <em>Start To Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start To Start</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType#getStartToStart()
   * @see #getWorkSequenceType()
   * @generated
   */
  EAttribute getWorkSequenceType_StartToStart();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToStart <em>Finish To Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Finish To Start</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToStart()
   * @see #getWorkSequenceType()
   * @generated
   */
  EAttribute getWorkSequenceType_FinishToStart();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getStartToFinish <em>Start To Finish</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start To Finish</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType#getStartToFinish()
   * @see #getWorkSequenceType()
   * @generated
   */
  EAttribute getWorkSequenceType_StartToFinish();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToFinish <em>Finish To Finish</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Finish To Finish</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToFinish()
   * @see #getWorkSequenceType()
   * @generated
   */
  EAttribute getWorkSequenceType_FinishToFinish();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimplePDLFactory getSimplePDLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ProcessImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__NAME = eINSTANCE.getProcess_Name();

    /**
     * The meta object literal for the '<em><b>Process Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__PROCESS_ELEMENTS = eINSTANCE.getProcess_ProcessElements();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ProcessElementImpl <em>Process Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ProcessElementImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getProcessElement()
     * @generated
     */
    EClass PROCESS_ELEMENT = eINSTANCE.getProcessElement();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.GuidanceImpl <em>Guidance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.GuidanceImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getGuidance()
     * @generated
     */
    EClass GUIDANCE = eINSTANCE.getGuidance();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUIDANCE__ELEMENTS = eINSTANCE.getGuidance_Elements();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUIDANCE__TEXT = eINSTANCE.getGuidance_Text();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl <em>Work Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkDefinition()
     * @generated
     */
    EClass WORK_DEFINITION = eINSTANCE.getWorkDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__NAME = eINSTANCE.getWorkDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Resources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__RESOURCES = eINSTANCE.getWorkDefinition_Resources();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl <em>Work Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.WorkSequenceImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequence()
     * @generated
     */
    EClass WORK_SEQUENCE = eINSTANCE.getWorkSequence();

    /**
     * The meta object literal for the '<em><b>Link Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__LINK_TYPE = eINSTANCE.getWorkSequence_LinkType();

    /**
     * The meta object literal for the '<em><b>Predecessor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__PREDECESSOR = eINSTANCE.getWorkSequence_Predecessor();

    /**
     * The meta object literal for the '<em><b>Successor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__SUCCESSOR = eINSTANCE.getWorkSequence_Successor();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ResourceImpl <em>Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ResourceImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getResource()
     * @generated
     */
    EClass RESOURCE = eINSTANCE.getResource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESOURCE__NAME = eINSTANCE.getResource_Name();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESOURCE__QUANTITY = eINSTANCE.getResource_Quantity();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ACResourceImpl <em>AC Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ACResourceImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getACResource()
     * @generated
     */
    EClass AC_RESOURCE = eINSTANCE.getACResource();

    /**
     * The meta object literal for the '<em><b>Resource</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AC_RESOURCE__RESOURCE = eINSTANCE.getACResource_Resource();

    /**
     * The meta object literal for the '<em><b>Resource Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AC_RESOURCE__RESOURCE_QUANTITY = eINSTANCE.getACResource_ResourceQuantity();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.WorkSequenceTypeImpl <em>Work Sequence Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.WorkSequenceTypeImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequenceType()
     * @generated
     */
    EClass WORK_SEQUENCE_TYPE = eINSTANCE.getWorkSequenceType();

    /**
     * The meta object literal for the '<em><b>Start To Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE_TYPE__START_TO_START = eINSTANCE.getWorkSequenceType_StartToStart();

    /**
     * The meta object literal for the '<em><b>Finish To Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE_TYPE__FINISH_TO_START = eINSTANCE.getWorkSequenceType_FinishToStart();

    /**
     * The meta object literal for the '<em><b>Start To Finish</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE_TYPE__START_TO_FINISH = eINSTANCE.getWorkSequenceType_StartToFinish();

    /**
     * The meta object literal for the '<em><b>Finish To Finish</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE_TYPE__FINISH_TO_FINISH = eINSTANCE.getWorkSequenceType_FinishToFinish();

  }

} //SimplePDLPackage
