/**
 * generated by Xtext 2.36.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Sequence Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequenceType#getStartToStart <em>Start To Start</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToStart <em>Finish To Start</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequenceType#getStartToFinish <em>Start To Finish</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToFinish <em>Finish To Finish</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequenceType()
 * @model
 * @generated
 */
public interface WorkSequenceType extends EObject
{
  /**
   * Returns the value of the '<em><b>Start To Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start To Start</em>' attribute.
   * @see #setStartToStart(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequenceType_StartToStart()
   * @model
   * @generated
   */
  String getStartToStart();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getStartToStart <em>Start To Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start To Start</em>' attribute.
   * @see #getStartToStart()
   * @generated
   */
  void setStartToStart(String value);

  /**
   * Returns the value of the '<em><b>Finish To Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finish To Start</em>' attribute.
   * @see #setFinishToStart(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequenceType_FinishToStart()
   * @model
   * @generated
   */
  String getFinishToStart();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToStart <em>Finish To Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finish To Start</em>' attribute.
   * @see #getFinishToStart()
   * @generated
   */
  void setFinishToStart(String value);

  /**
   * Returns the value of the '<em><b>Start To Finish</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start To Finish</em>' attribute.
   * @see #setStartToFinish(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequenceType_StartToFinish()
   * @model
   * @generated
   */
  String getStartToFinish();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getStartToFinish <em>Start To Finish</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start To Finish</em>' attribute.
   * @see #getStartToFinish()
   * @generated
   */
  void setStartToFinish(String value);

  /**
   * Returns the value of the '<em><b>Finish To Finish</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finish To Finish</em>' attribute.
   * @see #setFinishToFinish(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequenceType_FinishToFinish()
   * @model
   * @generated
   */
  String getFinishToFinish();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequenceType#getFinishToFinish <em>Finish To Finish</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finish To Finish</em>' attribute.
   * @see #getFinishToFinish()
   * @generated
   */
  void setFinishToFinish(String value);

} // WorkSequenceType
